### PR TITLE
Update stax to 6.2.1/4.2.1

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by lukasj** [comment]
...and I haven't found CQs

**Comment by arjantijms** [comment]
> Without that in place, this change is too risky

The 3.0.0 version of Metro will be tested anyway in GF. So if something would fail there due to these updates, it'll come back here anyway.

**Comment by lukasj** [comment]
> > Without that in place, this change is too risky
> 
> The 3.0.0 version of Metro will be tested anyway in GF. So if something would fail there due to these updates, it'll come back here anyway.

Who is going to fix what comes back? Why there are tests in place when nobody runs them? Why do you think GF is the only Metro consumer? Who is going to file CQs?

**Comment by arjantijms** [comment]
> Who is going to fix what comes back? 

We

> Why there are tests in place when nobody runs them? 

Tests for GlassFish are always run, but not now since this is a very special case of being dead-locked on a tangled web of dependencies. We first integrate everything, then so that it at least compiles, then starts-up, then deploys/runs admin console, then (wink wink) passed tests again.

> Why do you think GF is the only Metro consumer? 

It's not the only, but since it certifies for Jakarta EE 9 probably the first. So a Metro 3.0.0-M4 can be temporarily broken somewhat, since at this point really the only purpose of those milestones is to use it in GF. Hence why it might have been better to keep them in staging only, as we do with most components.

> Who is going to file CQs?

We, once everything runs we can CQ everything and anything that's applicable for CQ'ing. There's this issue on the board for it: https://github.com/eclipse-ee4j/glassfish/issues/23027

**Comment by arjantijms** [comment]
> Provide test results for:
> xml ws TCKs
> soap TCKs
> jax-ws unit tests on Tomcat 10 M5 or newer
> preferably also for
> metro e2e tests
> GlassFish QL

The entire point of having a milestone release (in staging only) is to be able to run exactly those things.

Without it, it's a little like chicken and egg. 

You don't have to fear milestone staged releases. They can be removed at will, and will even expire after 60 days and then will be gone for good.

**Comment by lukasj** [comment]
> > Why there are tests in place when nobody runs them?
> 
> Tests for GlassFish are always run, but not now

this is exactly the reason non-trivial amount of time has been put into resurrecting applicable testing at the metro level. Also what is so difficult on running sth like: `mvn -U -C clean install -Poss-release -Dws.transport=TOMCAT_LOCAL -Dtomcat.home=/Users/lukas/tmp/bugs/metro/apache-tomcat-10.0.0-M5` locally and sharing results? Same can be done for metro-wsit (one can use dep on jaxws SNAPSHOT locally in order to run tests here), it only takes longer.

> 
> > Why do you think GF is the only Metro consumer?
> 
> It's not the only, but since it certifies for Jakarta EE 9 probably the first.

One does not need that if all he wants is to consume existing service in some SE app on JDK 11

> So a Metro 3.0.0-M4 can be temporarily broken somewhat, since at this point really the only purpose of those milestones is to use it in GF. Hence why it might have been better to keep them in staging only, as we do with most components.

Why snapshot cannot be used till some M build appears in central? Is ~1-2weeks between them too much?

How do you expect issues like https://issues.apache.org/jira/browse/SANTUARIO-548 to become fixed if everything is kept in staging only?

> 
> > Who is going to file CQs?
> 
> We, once everything runs we can CQ everything and anything that's applicable for CQ'ing. There's this issue on the board for it: [eclipse-ee4j/glassfish#23027](https://github.com/eclipse-ee4j/glassfish/issues/23027)

that covers GlassFish, not metro project; each project _must_ have it's own CQ, the only difference is that those filed later can piggy back the one filed first if their use of such dependency is the same. Also note that usually micro updates are covered by one CQ

**Pull request merged**
